param(
  [string]$RepoRoot="."
)

Set-StrictMode -Version Latest
$ErrorActionPreference="Stop"

. (Join-Path $PSScriptRoot "lib/core.ps1")

$masterPath = Join-Path $RepoRoot "plans/master_plan.md"
if (-not (Test-Path $masterPath)) { throw "Missing: plans/master_plan.md" }

$master = Read-ManifestJsonFromMarkdown -Path $masterPath -StartMarker "---master_manifest---" -EndMarker "---end_master_manifest---"
if ($null -eq $master) { throw "Missing master manifest in plans/master_plan.md" }

$phaseIds = @($master.phases)
if ($phaseIds.Count -eq 0) { throw "Master manifest has no phases." }

# Load templates directly from policy (init should work before compile)
$tplPath = Join-Path $RepoRoot "policy/templates.md"
$tpl = Read-ManifestJsonFromMarkdown -Path $tplPath -StartMarker "---templates_manifest---" -EndMarker "---end_templates_manifest---"
$templates = $tpl.templates

function Get-TemplateForKey {
  param([string]$RelPath)
  foreach ($key in $templates.PSObject.Properties.Name) {
    if (Test-Glob -Path $RelPath -Glob $key) { return $templates.$key }
  }
  return $null
}

$created = 0
foreach ($id in $phaseIds) {
  $rel = "plans/$id.md"
  $abs = Join-Path $RepoRoot ("plans\{0}.md" -f $id)
  if (Test-Path $abs) { continue }

  $tplPhase = Get-TemplateForKey -RelPath $rel
  $sections = @()
  if ($null -ne $tplPhase) { $sections = @($tplPhase.required_sections) }

  # Default depends_on: previous phase in list
  $depends = @()
  $idx = [Array]::IndexOf($phaseIds, $id)
  if ($idx -gt 0) { $depends = @($phaseIds[$idx-1]) }

  $manifest = [ordered]@{
    id = $id
    status = "PENDING"
    depends_on = $depends
    intent = @("(fill in)")
    guard = [ordered]@{
      allowed_roots = @("apps/","scripts/","plans/","policy/","build/")
      allowed_ops = @("create","edit")
      forbidden_patterns = @("node_modules/**","artifacts/**")
    }
    inventory = [ordered]@{
      must_exist = @($rel)
      may_exist  = @("apps/**")
    }
    stop_conditions = @("plan_guard_passes")
    acceptance_tests = @("plan guard returns exit 0")
  } | ConvertTo-Json -Depth 50

  $lines = @()
  $lines += "# $id"
  $lines += ""
  $lines += "---phase_manifest---"
  $lines += $manifest
  $lines += "---end_phase_manifest---"
  $lines += ""
  foreach ($s in $sections) {
    $lines += $s
    $lines += ""
  }
  $lines += "## Notes"
  $lines += "Generated by plan init."

  Write-TextFile -Path $abs -Text ($lines -join "`n")
  $created++
  Write-Host "Created: $rel"
}

Write-Host "OK: plan init complete. created=$created"