param(
  [string]$RepoRoot = "."
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "lib/core.ps1")

$cfg = (Get-Content -LiteralPath (Join-Path $RepoRoot ".plan_guard/config.json") -Raw -Encoding UTF8) | ConvertFrom-Json -Depth 50
$bundlePath = Join-Path $RepoRoot $cfg.bundle_path
if (-not (Test-Path $bundlePath)) { throw "Missing bundle. Run compile first: $($cfg.bundle_path)" }
$bundle = (Get-Content -LiteralPath $bundlePath -Raw -Encoding UTF8) | ConvertFrom-Json -Depth 80

$active = ($bundle.phases | Where-Object { $_.id -eq $bundle.active_phase_id })
if ($null -eq $active) { throw "Active phase not found in bundle: $($bundle.active_phase_id)" }

$templates = $bundle.policy.templates.templates

function Get-TemplateForPath {
  param([Parameter(Mandatory=$true)][string]$RelPath)

  foreach ($key in $templates.PSObject.Properties.Name) {
    # Convert template keys like "plans/phase_*.md" to glob and test
    if (Test-Glob -Path $RelPath -Glob $key) {
      return $templates.$key
    }
  }
  return $null
}

function Ensure-RequiredSections {
  param(
    [Parameter(Mandatory=$true)][string]$RelPath
  )

  $tpl = Get-TemplateForPath -RelPath $RelPath
  if ($null -eq $tpl) { return $false }

  $abs = Join-Path $RepoRoot ($RelPath -replace "/","\")
  if (-not (Test-Path $abs)) { return $false }

  $txt = Read-TextUtf8 $abs
  $changed = $false

  foreach ($sec in $tpl.required_sections) {
    if ($txt -notmatch [Regex]::Escape($sec)) {
      # Append missing required sections at the end in a deterministic order
      $txt = $txt.TrimEnd() + "`n`n$sec`n"
      $changed = $true
    }
  }

  if ($changed) {
    Write-TextFile -Path $abs -Text $txt
  }
  return $changed
}

# Create required files if missing (deterministic skeletons)
foreach ($p in $active.inventory.must_exist) {
  $rel = Normalize-PathForBundle $p
  $abs = Join-Path $RepoRoot ($rel -replace "/","\")
  if (-not (Test-Path $abs)) {
    $tpl = Get-TemplateForPath -RelPath $rel

    if ($null -ne $tpl) {
      $lines = @()
      $lines += "# AUTO-GENERATED: $rel"
      $lines += ""
      $lines += "Generated by Plan Assembler (required by inventory.must_exist)."
      $lines += ""
      foreach ($sec in $tpl.required_sections) {
        $lines += $sec
        $lines += ""
      }
      Write-TextFile -Path $abs -Text ($lines -join "`n")
    } else {
      $content = @()
      $content += "# AUTO-GENERATED PLACEHOLDER"
      $content += ""
      $content += "This file was created by Plan Assembler because it is required by the active phase inventory."
      $content += ""
      Write-TextFile -Path $abs -Text ($content -join "`n")
    }

    Write-Host "Created missing required file: $rel"
  }
}

# Enforce template required sections for files that exist
$sectionFixes = 0
foreach ($p in $active.inventory.must_exist) {
  $rel = Normalize-PathForBundle $p
  if (Ensure-RequiredSections -RelPath $rel) {
    $sectionFixes++
    Write-Host "Patched required sections: $rel"
  }
}

# Baseline snapshot for active phase (if missing)
$baselineDir = Join-Path $RepoRoot $cfg.baseline_dir
if (-not (Test-Path $baselineDir)) { New-Item -ItemType Directory -Force -Path $baselineDir | Out-Null }
$baselinePath = Join-Path $baselineDir ("{0}.json" -f $bundle.active_phase_id)

if (-not (Test-Path $baselinePath)) {
  $exclude = @($bundle.policy.exclusions.exclude)

  $files = Get-ChildItem -LiteralPath $RepoRoot -Recurse -File | ForEach-Object {
    $rel2 = Normalize-PathForBundle ($_.FullName.Substring((Resolve-Path $RepoRoot).Path.Length).TrimStart("\","/"))
    if ($rel2 -eq "" -or $rel2.StartsWith(".git/")) { return }
    if (Any-GlobMatch -Path $rel2 -Globs $exclude) { return }

    [ordered]@{
      path = $rel2
      length = $_.Length
      sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash
    }
  } | Where-Object { $_ -ne $null }

  $baseline = [ordered]@{
    phase_id = $bundle.active_phase_id
    created_at_utc = (Get-Date).ToUniversalTime().ToString("o")
    bundle_generated_at_utc = $bundle.generated_at_utc
    files = $files
  }

  Write-JsonFile -Path $baselinePath -Object $baseline
  Write-Host "Baseline created: $($cfg.baseline_dir)/$($bundle.active_phase_id).json"
} else {
  Write-Host "Baseline exists: $($cfg.baseline_dir)/$($bundle.active_phase_id).json"
}

Write-Host "OK: assemble complete. (section fixes: $sectionFixes)"